// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package storage

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users(email, password)
values ($1, $2)
returning email, password, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, db DBTX, email string, password string) (User, error) {
	row := db.QueryRow(ctx, createUser, email, password)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
