### Get a tile by its ID
POST {{host}}/tiles/GetTile
Accept: application/json
Content-Type: application/json

{
  "id": 2
}


### Create a tile without owner
POST {{host}}/tiles/CreateTile
Content-Type: application/json

{
  "x": 2,
  "y": 1,
  "title": "Cat Shop",
  "subtitle": "Deposit your cats here",
  "link": "tel:+989109403234",
  "image": "https://ehsandar.top"
}
