services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=baldosa
      - POSTGRES_USER=baldosa
      - POSTGRES_PASSWORD=complex_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U baldosa" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.1-bookworm
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - "9000:9000"   # MinIO Console
      - "9001:9001"   # MinIO Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BALDOSA_DATABASE__CONN_STRING=postgresql://baldosa:complex_password@db:5432/baldosa?sslmode=disable
      - BALDOSA_S3_CLIENT__ENDPOINT=minio:9000
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - db
      - redis
