### Get a tile by its ID
POST {{host}}/tiles/GetTile
Accept: application/json
Content-Type: application/json

{
  "id": 2
}


### Create a tile without owner
POST {{host}}/tiles/CreateTile
Content-Type: application/json

{
  "x": 2,
  "y": 1,
  "title": "Cat Shop",
  "subtitle": "Deposit your cats here",
  "link": "tel:+989109403234",
  "image": "https://ehsandar.top"
}

### Get tiles in a specific area
POST {{host}}/tiles/GetTileRange
Content-Type: application/json

{
  "x_low": -10,
  "y_low": -10,
  "x_high": 10,
  "y_high": 10
}

### Get image upload URL
POST {{host}}/tiles/PrepImageUpload
Content-Type: application/json

{
  "content_type": "image/png"
}

> {%
  client.global.set("upload_url", response.body.upload_url);
%}

### Upload image
PUT {{upload_url}}
Content-Type: image/png

< ./sample.png
