### Get a tile by its coordinates
GET {{host}}/tiles/{{x}}/{{y}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Purchase a tile
POST {{host}}/tiles/{{x}}/{{y}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Create tile image
POST {{host}}/tiles/{{x}}/{{y}}/images
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content_type": "image/jpeg"
}

> {%
  client.global.set("upload_url", response.body.upload_url);
%}


### Upload image
PUT {{upload_url}}
Content-Type: image/jpeg

< ./sample.png


### Edit a tile
PUT {{host}}/tiles/{{x}}/{{y}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Pipes Shop",
  "subtitle": "The best pipes in town",
  "link": "https://pipes.com"
}

### Get the tile map at a coordination
GET {{host}}/tiles/map/0/256
Accept: application/octet-stream
Authorization: Bearer {{simple_key}}
